version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/rails
    environment:
      RAILS_ENV: production
      REDIS_URL: redis://redis:6379/0
    ports:
      - "3000:3000"
    depends_on:
      - redis
    command: >
      sh -c "bin/rails db:migrate && bin/rails server -b 0.0.0.0"

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/rails
    environment:
      RAILS_ENV: production
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
    command: >
      bundle exec sidekiq -e production -C config/sidekiq.yml

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
