version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: my_app_test
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
    environment:
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: 123
      DB_NAME: my_app_test
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
volumes:
  pgdata:
