default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 123
  host: localhost
  port: 5432

development:
  <<: *default
  database: my_app_development

test:
  <<: *default
  database: my_app_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>

cable:
  <<: *default
  database: <%= ENV['CABLE_DB_NAME'] || ENV['DB_NAME'] %>
  username: <%= ENV['CABLE_DB_USERNAME'] || ENV['DB_USERNAME'] %>
  password: <%= ENV['CABLE_DB_PASSWORD'] || ENV['DB_PASSWORD'] %>
  host: <%= ENV['CABLE_DB_HOST'] || ENV['DB_HOST'] %>
  port: <%= ENV['CABLE_DB_PORT'] || ENV['DB_PORT'] %>
